### ISSUE TITLE
Shiva sammed me for 400$ paid rat.

### ISSUE THREAD

**Issue by jrnassarr** [shivaya-dav/DogeRat-Premium#1]
![image](https://github.com/shivaya-dav/DogeRat-Premium/assets/110086147/cf4e2120-52c7-4608-8e8b-2939c3cbe4bf)
He is a scammer beware of him.  
He scammed me for 400$ and promised for paid rat and he didn't deliver anything and he blocked me and kicked me from his own group. 
He ia a scammer 
Scammer don't deal with him.

**Comment by shivaya-dav** [comment]
F
